# Site settings
title: Lara's Tech and Sustainability Journey
email: larasundare@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Welcome to my blog where I share my journey in DevOps, tech consulting, and sustainability. Join me as I explore ethical AI, green computing, developer experience, and sustainable tech practices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lara-sundare6.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: lara-sundare6

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Social links (optional)
social:
  github: https://github.com/lara-sundare6
  linkedin: https://www.linkedin.com/in/lara-sundare6/

# Other configurations
permalink: /:categories/:year/:month/:day/:title:output_ext
